### ISSUE TITLE
求救train_pretrain.py：RuntimeError: CUDA error: device kernel image is invalid

### ISSUE THREAD

**Issue by WingsLong** [jingyaogong/minimind#199]
Traceback (most recent call last):
  File "/data/aigc/model_train/minimind/train_pretrain.py", line 169, in <module>
    model, tokenizer = init_model(lm_config)
  File "/data/aigc/model_train/minimind/train_pretrain.py", line 100, in init_model
    model = MiniMindLM(lm_config).to(args.device)
  File "/data/programs/python310/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2960, in to
    return super().to(*args, **kwargs)
  File "/data/programs/python310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1175, in to
    return self._apply(convert)
  File "/data/programs/python310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/data/programs/python310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/data/programs/python310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1161, in convert
    return t.to(
RuntimeError: CUDA error: device kernel image is invalid
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

大佬，请求，运行训练的脚本python train_pretrain.py ，搞了一下午没看出啥问题！
系统：CentOS 7
CUDA：11.8
PyTorch：2.3.1
显卡：Tesla T4

**Comment by jingyaogong** [comment]
可能是cuda版本和torch不匹配

**Comment by WingsLong** [comment]
> 可能是cuda版本和torch不匹配

环境在微调和部署大模型都没有问题，看版本都是匹配的，不知道啥原因

**Comment by WingsLong** [comment]
> > 可能是cuda版本和torch不匹配
> 
> 环境在微调和部署大模型都没有问题，看版本都是匹配的，不知道啥原因

# pip list | grep torch
torch                                    2.3.1+cu118
torchaudio                               2.3.1+cu118
torchvision                              0.18.1+cu118

# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

**Comment by jingyaogong** [comment]
126行的
```
parser.add_argument("--dtype", type=str, default="bfloat16")
```

更改float16/float32重试结果

**Comment by WingsLong** [comment]
> 126行的
> 
> ```
> parser.add_argument("--dtype", type=str, default="bfloat16")
> ```
> 
> 更改float16/float32重试结果

都试过了，都不行，对比其他初始化model的数据来看embedding里面的embeddings.weight缺少device这个参数，但加上其他地方又继续报这个，根本改不完，感觉方向不对

**Comment by jingyaogong** [comment]
启动脚本是什么，代码有无改动

**Comment by WingsLong** [comment]
> 启动脚本是什么，代码有无改动

就直接运行：python train_pretrain.py 
改了flash_attn 为 False，因为T4不支持，没安装所以关闭了

**Comment by jingyaogong** [comment]
那这个问题目测还是环境的问题

```
import torch

if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.randn(10, 10).to(device)
    y = torch.randn(10, 10).to(device)
    z = torch.matmul(x, y)
    print(z)
    print("CUDA is working!")
else:
    print("CUDA is NOT available!")
```

测试一下

**Comment by WingsLong** [comment]
> import torch
> 
> if torch.cuda.is_available():
>     device = torch.device("cuda:0")
>     x = torch.randn(10, 10).to(device)
>     y = torch.randn(10, 10).to(device)
>     z = torch.matmul(x, y)
>     print(z)
>     print("CUDA is working!")
> else:
>     print("CUDA is NOT available!")

tensor([[  7.7300,   2.5682,   7.3701,   3.4798,  -3.7759,  -6.8200,  -6.4130,
          -3.7229,   3.4061,  -3.8279],
        [  2.5537,   9.4985,  -3.5063,  -0.9773,   2.1598,   3.4471,   7.1763,
          -0.9553,  -1.6271,  -5.5354],
        [ -0.3957,  -0.5845,  -4.4748,  -0.4031,   0.9073,   2.5919,  -0.6374,
           2.1821,  -0.6097,   4.1278],
        [ -1.0536,   1.3892,  -4.5976,   1.8106,  -0.1424,  -5.1722,   1.0626,
          -5.9555,   4.1127,  -6.0812],
        [ -0.7480,   2.8077,  -3.2948,   3.9045,  -2.7811,  -5.0853,   3.5890,
          -5.6535,   0.2564, -10.0337],
        [  2.6233,   9.8837,   2.3371,  -0.4072,  -2.9862,  -4.4930,   4.8555,
          -6.5515,  -1.2491,  -5.9747],
        [  1.5164,  -0.0186,  -1.7318,  -2.6537,  -0.1708,   3.0012,   0.0497,
           1.2559,  -0.9325,   1.8182],
        [ -5.5188,  -3.0373,  -3.7685,   3.3514,   0.3750,  -1.7463,   1.7318,
           0.2118,  -1.3748,  -8.0784],
        [ -1.4784,  -3.8761,   1.3504,   2.6007,   0.0135,  -1.7795,  -2.5676,
           1.1180,   1.3169,  -0.6828],
        [  6.6876,   3.4077,   2.7332,  -3.9619,  -1.2673,   5.7042,   2.2003,
          -2.0889,   1.3573,   7.9879]], device='cuda:0')
CUDA is working!
可以正常运行的，只能重装个环境看看了，无解，可能是T4的问题？
